const GEO_URL =
  "https://raw.githubusercontent.com/octerv/react-statistics-jpmap/master/mapdata/jp-prefectures.json";

const PREFECTURE_DICT = {
  1: { en: "Hokkaido", jp: "北海道" },
  2: { en: "Aomori", jp: "青森県" },
  3: { en: "Iwate", jp: "岩手県" },
  4: { en: "Miyagi", jp: "宮城県" },
  5: { en: "Akita", jp: "秋田県" },
  6: { en: "Yamagata", jp: "山形県" },
  7: { en: "Fukushima", jp: "福島県" },
  8: { en: "Ibaraki", jp: "茨城県" },
  9: { en: "Tochigi", jp: "栃木県" },
  10: { en: "Gunma", jp: "群馬県" },
  11: { en: "Saitama", jp: "埼玉県" },
  12: { en: "Chiba", jp: "千葉県" },
  13: { en: "Tokyo", jp: "東京都" },
  14: { en: "Kanagawa", jp: "神奈川県" },
  15: { en: "Niigata", jp: "新潟県" },
  16: { en: "Toyama", jp: "富山県" },
  17: { en: "Ishikawa", jp: "石川県" },
  18: { en: "Fukui", jp: "福井県" },
  19: { en: "Yamanashi", jp: "山梨県" },
  20: { en: "Nagano", jp: "長野県" },
  21: { en: "Gifu", jp: "岐阜県" },
  22: { en: "Shizuoka", jp: "静岡県" },
  23: { en: "Aichi", jp: "愛知県" },
  24: { en: "Mie", jp: "三重県" },
  25: { en: "Shiga", jp: "滋賀県" },
  26: { en: "Kyoto", jp: "京都府" },
  27: { en: "Osaka", jp: "大阪府" },
  28: { en: "Hyogo", jp: "兵庫県" },
  29: { en: "Nara", jp: "奈良県" },
  30: { en: "Wakayama", jp: "和歌山県" },
  31: { en: "Tottori", jp: "鳥取県" },
  32: { en: "Shimane", jp: "島根県" },
  33: { en: "Okayama", jp: "岡山県" },
  34: { en: "Hiroshima", jp: "広島県" },
  35: { en: "Yamaguchi", jp: "山口県" },
  36: { en: "Tokushima", jp: "徳島県" },
  37: { en: "Kagawa", jp: "香川県" },
  38: { en: "Ehime", jp: "愛媛県" },
  39: { en: "Kochi", jp: "高知県" },
  40: { en: "Fukuoka", jp: "福岡県" },
  41: { en: "Saga", jp: "佐賀県" },
  42: { en: "Nagasaki", jp: "長崎県" },
  43: { en: "Kumamoto", jp: "熊本県" },
  44: { en: "Oita", jp: "大分県" },
  45: { en: "Miyazaki", jp: "宮崎県" },
  46: { en: "Kagoshima", jp: "鹿児島県" },
  47: { en: "Okinawa", jp: "沖縄県" },
};

export { GEO_URL, PREFECTURE_DICT };
